name: Publish Blog to Amazon S3

on:
  push:
    branches:
      - master

jobs:
  publish-s3:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Make gradlew executable
        run: chmod +x ./build/gradlewCustom
      - name: Build with Gradle
        env: # Or as an environment variable
         LICENSE_KEY: ${{secrets.LICENSE_KEY}}
        run: |
          cd ./build
          ./gradlewCustom --info --stacktrace

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          destination_dir: 'blog'
          source_dir: './site'
